import React, { useState } from 'react';
import { Check, Copy, Gift, Users } from 'lucide-react';
import { useSpotOn } from '../../context/SpotOnContext';

export const ReferralDashboard: React.FC = () => {
  const { entitlements, copyReferralLink, showToast } = useSpotOn();
  const [copied, setCopied] = useState(false);
  const referrals = entitlements.successfulReferrals;
  const copy = async () => { const ok = await copyReferralLink(); if (ok) { setCopied(true); showToast('Invite link copied'); window.setTimeout(() => setCopied(false), 1800); } };
  return <section className="rounded-3xl border border-blue-100 bg-blue-50/70 p-5 dark:border-blue-900/50 dark:bg-blue-950/25"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-blue-600 text-white"><Gift className="size-5" /></div><div><h3 className="font-bold text-slate-900 dark:text-white">Share the calmer way to track</h3><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">Verified referrals unlock rewards. We only count a referral after a new account is confirmed.</p></div></div><Users className="size-5 text-blue-600" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/80 p-4 dark:bg-slate-900/60"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Progress to Premium</p><p className="mt-1 text-lg font-bold text-slate-900 dark:text-white">{Math.min(referrals, 3)} / 3 verified</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, referrals / 3 * 100)}%` }} /></div></div><div className="rounded-2xl bg-white/80 p-4 dark:bg-slate-900/60"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Lifetime reward</p><p className="mt-1 text-lg font-bold text-slate-900 dark:text-white">{Math.min(referrals, 10)} / 10 verified</p><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">Current access: <span className="font-bold capitalize">{entitlements.plan}</span></p></div></div><button type="button" onClick={() => void copy()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-2xl border border-blue-200 bg-white px-4 py-3 text-sm font-bold text-blue-700 hover:bg-blue-100 dark:border-blue-800 dark:bg-slate-900 dark:text-blue-300">{copied ? <Check className="size-4" /> : <Copy className="size-4" />}{copied ? 'Copied' : 'Copy invite link'}</button></section>;
};
